products = [
    {
        '_id': '1',
        'name': 'Move',
        'image': '/images/move.jpg',
        'description':
        'Move, considéré comme un classique par notre clientèle, n’exige aucun prérequis, le programme comporte des exercices de stretching et mobilité facile et des  routines à faire chaque jour pour rester en bonne santé.',
        'brand': 'Move',
        'category': 'Book',
        'price': 24.99,
        'countInStock': 50,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Barres Protéine de graines de courge',
        'image': '/images/prot-7.jpg',
        'description':
        'Boîte contenant 3 barres de 25g. Contient l équivalent en protéine d un œuf. Texture moelleuse et facile manger. drapeau france Fabriquée en France. Ingrédients Bio & naturels. Des ingrédients nobles, rassasiants et digestes. Sans sucre ajouté, est uniquement présent le sucre du fruit. Sans gluten et sans lactose. Naturellement riche en antioxydants. A consommer après un entrainement, une compétition ou un complément protéinée. Recette élaborée par un chef 2** au guide Michelin. 1 barre = 97 kcal.',
        'brand': 'Abricot - Romarin BAOUW	Protéine',
        'category': 'Protéine',
        'price': 7.99,
        'countInStock': 12,
        'rating': 4.0,
        'numReviews': 8,
    },
    {
        '_id': '3',
        'name': 'MÛRES BLANCHES BIO',
        'image': '/images/prot-6.jpg',
        'description':
        'C’est un programme dédié aux personnes ayant un niveau intermédiaire dans le but  d’augmenter leurs forces, endurance et leur apprendre des nouvelles techniques. Les prérequis seront notés sur la description.',
        'brand': 'MÛRES BLANCHES BIO',
        'category': 'Protéine',
        'price': 7.99,
        'countInStock': 50,
        'rating': 3,
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'Barre Ultra Energy',
        'image': '/images/prot-8.jpg',
        'description':
        'Barre énergétique moelleuse et croustillante au goût fruité de fruits rouges et noix. 7g de protéines végétales constituées de tous les acides aminés. Ratio glucide/protéines 4:1 idéal pour l endurance.180mg d électrolytes améliorant l hydratation. Digestion facile évitant les malaises gastro-intestinaux. Ingrédients naturels et sans OGM 190 kcal pour un effort intense de 45 minutes.',
        'brand': 'Baies et Noix Naak',
        'category': 'Protéine',
        'price': 3.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '5',
        'name': 'Healthy Cook',
        'image': '/images/healthy-cook.jpg',
        'description':
        'C est un livre électronique sur l’alimentation qui couvre toutes  les bases nécessaires sur la nutrition avec des recettes faciles et rapides à faire.',
        'brand': 'Healthy Cook',
        'category': 'Book',
        'price': 29.99,
        'countInStock': 7,
        'rating': 3.5,
        'numReviews': 10,
    },
    {
        '_id': '6',
        'name': 'Master the Front lever',
        'image': '/images/Master-the-frontLever.jpg',
        'description':
        'C est un livre électronique qui explique étapes, exercices  et progression à suivre pour réussir cette figure.',
        'brand': 'Master the Front lever',
        'category': 'Book',
        'price': 39.99,
        'countInStock': 50,
        'rating': 4,
        'numReviews': 12,
    },
    {
        '_id': '7',
        'name': 'Zero to Hero',
        'image': '/images/zero-to-hero.jpg',
        'description':
        'C est un livre électronique qui parle en détails sur les différentes  techniques utilisées pour augmenter sa force physique et mentale ainsi que des  astuces pour mieux s’organiser et se concentrer sur ses objectifs que ce soit dans  le sport, le travail, ou la vie quotidienne.',
        'brand': 'Zero to Hero',
        'category': 'Book',
        'price': 39.99,
        'countInStock': 50,
        'rating': 4,
        'numReviews': 12,
    },
    {
        '_id': '8',
        'name': 'Master the Front lever',
        'image': '/images/Master-the-frontLever.jpg',
        'description':
        'C est un livre électronique qui explique étapes, exercices  et progression à suivre pour réussir cette figure.',
        'brand': 'Master the Front lever',
        'category': 'Book',
        'price': 39.99,
        'countInStock': 50,
        'rating': 4,
        'numReviews': 12,
    },
    {
        '_id': '9',
        'name': 'Master the Front lever',
        'image': '/images/Master-the-frontLever.jpg',
        'description':
        'C est un livre électronique qui explique étapes, exercices  et progression à suivre pour réussir cette figure.',
        'brand': 'Master the Front lever',
        'category': 'Book',
        'price': 39.99,
        'countInStock': 50,
        'rating': 4,
        'numReviews': 12,
    },
]
